In [57]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [58]:
df = pd.read_csv("heart.csv", sep=',',usecols=[0, 1, 2, 3, 4, 5,6, 7, 8, 9, 10, 11, 12, 13],
                    names=['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal','target'])


In [59]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak   
1     63    1   3       145   233    1        0      150      0      2.3   
2     37    1   2       130   250    0        1      187      0      3.5   
3     41    0   1       130   204    0        0      172      0      1.4   
4     56    1   1       120   236    0        1      178      0      0.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
299   57    0   0       140   241    0        1      123      1      0.2   
300   45    1   3       110   264    0        1      132      0      1.2   
301   68    1   0       144   193    1        1      141      0      3.4   
302   57    1   0       130   131    0        1      115      1      1.2   
303   57    0   1       130   236    0        0      174      0        0   

     slope  ca  thal  target  
0    slope  ca  thal  target  
1        0   0     1       1  
2        0   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
299      1   0     3       0  
300      1   0     3       0  
301      1   2     3       0  
302      1   1     3       0  
303      1   1     2       0  

[304 rows x 14 columns]

In [38]:
encode = LabelEncoder()
df['age'] = encode.fit_transform(df['age'])
df['sex'] = encode.fit_transform(df['sex'])
df['cp'] = encode.fit_transform(df['cp'])
df['trestbps'] = encode.fit_transform(df['trestbps'])
df['chol'] = encode.fit_transform(df['chol'])
df['fbs'] = encode.fit_transform(df['fbs'])
df['restecg'] = encode.fit_transform(df['restecg'])
df['thalach'] = encode.fit_transform(df['thalach'])
df['exang'] = encode.fit_transform(df['exang'])
df['oldpeak'] = encode.fit_transform(df['oldpeak'])
df['slope'] = encode.fit_transform(df['slope'])
df['ca'] = encode.fit_transform(df['ca'])
df['thal'] = encode.fit_transform(df['thal'])
df['target'] = encode.fit_transform(df['target'])

In [39]:
x = df.drop(["target"], axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   41    2   4        49   152    2        3       91      2       40      3   
1   29    1   3        30    64    1        0       42      0       22      0   
2    3    1   2        21    80    0        1       77      0       32      0   
3    7    0   1        21    35    0        0       64      0       14      2   
4   22    1   1        13    67    0        1       69      0        8      2   

   ca  thal  
0   5     4  
1   0     1  
2   0     2  
3   0     2  
4   0     2

In [40]:
y = df["target"]
y.head()

0    2
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 100)

In [50]:
nb = GaussianNB()

In [51]:
nb_train = nb.fit(x_train, y_train)

In [52]:
y_pred = nb_train.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0])

In [53]:
np.array(y_test)

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0])

In [54]:
nb_train.predict_proba(x_test)

array([[7.80163492e-02, 9.21983651e-01, 0.00000000e+00],
       [9.54214190e-01, 4.57858103e-02, 0.00000000e+00],
       [7.79288072e-02, 9.22071193e-01, 0.00000000e+00],
       [9.96070252e-01, 3.92974771e-03, 0.00000000e+00],
       [9.20562624e-02, 9.07943738e-01, 0.00000000e+00],
       [1.38817366e-01, 8.61182634e-01, 0.00000000e+00],
       [9.87705993e-01, 1.22940071e-02, 0.00000000e+00],
       [9.55025711e-01, 4.49742891e-02, 0.00000000e+00],
       [9.99996706e-01, 3.29401123e-06, 0.00000000e+00],
       [9.89225371e-01, 1.07746286e-02, 0.00000000e+00],
       [9.92851230e-01, 7.14876965e-03, 0.00000000e+00],
       [9.99998383e-01, 1.61651257e-06, 0.00000000e+00],
       [9.96242971e-01, 3.75702943e-03, 0.00000000e+00],
       [1.14114433e-02, 9.88588557e-01, 0.00000000e+00],
       [9.99975769e-01, 2.42310560e-05, 0.00000000e+00],
       [2.70605074e-01, 7.29394926e-01, 0.00000000e+00],
       [9.82988296e-01, 1.70117045e-02, 0.00000000e+00],
       [2.44279851e-01, 7.55720

In [55]:
confusion_matrix(y_test, y_pred)
f1_score(y_test, y_pred, labels=np.unique(y_pred), average='weighted')

0.9023893710489662

In [56]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.97      0.86      0.91        36\n           1       0.83      0.96      0.89        25\n\n    accuracy                           0.90        61\n   macro avg       0.90      0.91      0.90        61\nweighted avg       0.91      0.90      0.90        61\n'