In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [3]:
df = pd.read_csv("heart.csv", sep=',')


In [4]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [5]:
encode = LabelEncoder()
df['age'] = encode.fit_transform(df['age'])
df['sex'] = encode.fit_transform(df['sex'])
df['cp'] = encode.fit_transform(df['cp'])
df['trestbps'] = encode.fit_transform(df['trestbps'])
df['chol'] = encode.fit_transform(df['chol'])
df['fbs'] = encode.fit_transform(df['fbs'])
df['restecg'] = encode.fit_transform(df['restecg'])
df['thalach'] = encode.fit_transform(df['thalach'])
df['exang'] = encode.fit_transform(df['exang'])
df['oldpeak'] = encode.fit_transform(df['oldpeak'])
df['slope'] = encode.fit_transform(df['slope'])
df['ca'] = encode.fit_transform(df['ca'])
df['thal'] = encode.fit_transform(df['thal'])
df['target'] = encode.fit_transform(df['target'])

In [6]:
x = df.drop(["target"], axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   29    1   3        31    64    1        0       49      0       22      0   
1    3    1   2        22    80    0        1       84      0       32      0   
2    7    0   1        22    35    0        0       71      0       14      2   
3   22    1   1        14    67    0        1       76      0        8      2   
4   23    0   0        14   145    0        1       62      1        6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [7]:
y = df["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 100)

In [9]:
nb = GaussianNB()

In [10]:
nb_train = nb.fit(x_train, y_train)

In [11]:
y_pred = nb_train.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0])

In [12]:
np.array(y_test)

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [13]:
nb_train.predict_proba(x_test)

array([[2.94201316e-03, 9.97057987e-01],
       [9.99773855e-01, 2.26145224e-04],
       [9.99893025e-01, 1.06975265e-04],
       [7.23561347e-04, 9.99276439e-01],
       [3.86791206e-02, 9.61320879e-01],
       [9.99962990e-01, 3.70101806e-05],
       [9.10227858e-01, 8.97721419e-02],
       [9.58470987e-01, 4.15290129e-02],
       [6.10895486e-02, 9.38910451e-01],
       [5.92487609e-02, 9.40751239e-01],
       [9.79435670e-01, 2.05643297e-02],
       [3.99903550e-01, 6.00096450e-01],
       [9.91573324e-01, 8.42667560e-03],
       [1.97754468e-01, 8.02245532e-01],
       [9.94589690e-01, 5.41030999e-03],
       [6.17910807e-02, 9.38208919e-01],
       [7.11166722e-01, 2.88833278e-01],
       [9.97174010e-01, 2.82599028e-03],
       [9.92144834e-01, 7.85516621e-03],
       [2.70053446e-01, 7.29946554e-01],
       [7.83505094e-01, 2.16494906e-01],
       [6.99979029e-03, 9.93000210e-01],
       [9.95925396e-01, 4.07460389e-03],
       [2.78583547e-03, 9.97214165e-01],
       [4.496212

In [14]:
confusion_matrix(y_test, y_pred)
f1_score(y_test, y_pred, labels=np.unique(y_pred), average='weighted')

0.8526971777874807

In [15]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.90      0.82      0.86        33\n           1       0.81      0.89      0.85        28\n\n    accuracy                           0.85        61\n   macro avg       0.85      0.86      0.85        61\nweighted avg       0.86      0.85      0.85        61\n'