In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [17]:
df = pd.read_csv("heart.csv", sep=',')


In [18]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [19]:
x = df.drop(["target"], axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [20]:
y = df["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 100)

In [22]:
nb = GaussianNB()

In [23]:
nb_train = nb.fit(x_train, y_train)

In [24]:
y_pred = nb_train.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0])

In [25]:
np.array(y_test)

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [26]:
nb_train.predict_proba(x_test)

array([[3.03887240e-03, 9.96961128e-01],
       [9.99885428e-01, 1.14572395e-04],
       [9.99969551e-01, 3.04487633e-05],
       [6.39850429e-04, 9.99360150e-01],
       [3.95736632e-02, 9.60426337e-01],
       [9.99997115e-01, 2.88494566e-06],
       [9.10429268e-01, 8.95707319e-02],
       [9.56076047e-01, 4.39239530e-02],
       [5.31995800e-02, 9.46800420e-01],
       [7.12946840e-02, 9.28705316e-01],
       [9.78076504e-01, 2.19234959e-02],
       [3.80682580e-01, 6.19317420e-01],
       [9.92352146e-01, 7.64785394e-03],
       [2.07154482e-01, 7.92845518e-01],
       [9.95254418e-01, 4.74558184e-03],
       [6.99373993e-02, 9.30062601e-01],
       [6.94781419e-01, 3.05218581e-01],
       [9.97626498e-01, 2.37350170e-03],
       [9.91534301e-01, 8.46569900e-03],
       [2.27263604e-01, 7.72736396e-01],
       [7.90309587e-01, 2.09690413e-01],
       [6.12549140e-03, 9.93874509e-01],
       [9.97738372e-01, 2.26162794e-03],
       [2.78369465e-03, 9.97216305e-01],
       [5.184693

In [27]:
confusion_matrix(y_test, y_pred)
f1_score(y_test, y_pred, labels=np.unique(y_pred), average='weighted')

0.8690644431882419

In [28]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.90      0.85      0.88        33\n           1       0.83      0.89      0.86        28\n\n    accuracy                           0.87        61\n   macro avg       0.87      0.87      0.87        61\nweighted avg       0.87      0.87      0.87        61\n'